### PR TITLE
added file for Open Dial

### PR DESCRIPTION
**Pull request by HoffmannAJ**

### CODE REVIEW

**Comment by psibre** [comment]
@HoffmannAJ I think there are compilation problems with the raw XML blocks and inline. Please use [an appropriate LaTeX package](https://www.ctan.org/topic/listing) to include code; I recommend [`listings`](https://www.ctan.org/pkg/listings) or [`minted`](https://www.ctan.org/pkg/minted). It also has the benefit of formatting it nicely.

**Comment by HoffmannAJ** [comment]
@psibre  Thank you! I was indeed not using a proper package as the error message I got had confused me. 
(I got a message that indicated that there were problems with the chapter "reverberation recordings in the elevator").
After having changed some small things those messages disappeared as well when using the LaTex package. Therefore I hope that I have now gotten rid of all compilation problems.

The file still lacks citations. I will add these in the next revision.

**Comment by bryandeng** [comment]
@HoffmannAJ You misunderstood what @psibre said.

Just do like this:

```
\begin{minted}{xml}
<rule>
  <case>
    <condition operator="or">
      <if var="u_u" value="go to second floor" relation="contains"/>
      <if var="u_u" value="take me up to the second floor" relation="contains"/>
      <if var="u_u" value="second floor" relation="contains"/>
    </condition>
    <effect prob="1">
      <set var="a_u" value="Request(second)" />
    </effect>
  </case>
  <case>
    <condition operator="or">
      <if var="u_u" value="go to thrid floor" relation="contains"/>
      <if var="u_u" value="take me up to the third floor" relation="contains"/>
      <if var="u_u" value="third floor" relation="contains"/>
    </condition>
    <effect prob="1">
      <set var="a_u" value="Request(third)" />
    </effect>
  </case>
</rule>
\end{minted}
```

**Comment by naszka** [comment]
wow. i haven't seen this, and also wrote a section on it.... anyway, contentwise it is almost the same so let's just stick with this one,

**Pull request merged**
