### PR TITLE
ToDos and Ticket 80

### PR DESCRIPTION
**Pull request by HoffmannAJ**

### CODE REVIEW

**Comment by sirifarif** [comment]
Did you checkout  the latest report before changing it. I am seeing some old version of the file that you corrected.

**Comment by HoffmannAJ** [comment]
I did - or rather I tried to.
When I saw the graph on the github page I was a little confused, as it seems that my branch was not up to date at all. However I have the latest changes (the ModuleElla subsection from Laura) in my file.
Is there anything I can do to solve that problem?

**Comment by sirifarif** [comment]
In the current pull request, I see changes in the whole document, I am sure you don't intend these changes. So, I think a tacky was is to: 
1. Rename your modified tex file and save it  somewhere else.
2. Get the latest file from upstream/master and then copy and paste your changes one by one.
3. Make a pull request.

Is that Okay for you?

**Comment by sirifarif** [comment]
@HoffmannAJ : If you want me to merge, please respond to my previous comment.

**Pull request closed without merging**
